# Snapshot governance spaces mapped to their Binance trading symbols
spaces:
  aavedao.eth: AAVEUSDT
  uniswapgovernance.eth: UNIUSDT
  lido-snapshot.eth: LDOUSDT
  ens.eth: ENSUSDT
  arbitrumfoundation.eth: ARBUSDT
  opcollective.eth: OPUSDT
  balancer.eth: BALUSDT
  sushigov.eth: SUSHIUSDT
  curve.eth: CRVUSDT
  1inch.eth: 1INCHUSDT
